### ISSUE TITLE
Time Region Support

### ISSUE THREAD

**Issue by securenotebook** [marcusolsson/grafana-hourly-heatmap-panel#10]
Hi, 

Firstly thanks, this is an amazing plugin thanks again for your hard work. 

-- Enhancement request--
I would like to see all hours on the heatmap for a given day,  however, I'd like to add Time Regions to highlight normal operating hours were I expect to see data. ie: 9am to 5pm.

Standard Graph with Time Regions:
![Annotation 2020-09-07 113034](https://user-images.githubusercontent.com/734683/92346252-c8d54180-f0fe-11ea-85a6-519ab19444c0.png)

Same data in Hourly Heat Panel with additional time region added:
![Annotation 2020-09-07 112443](https://user-images.githubusercontent.com/734683/92346263-d38fd680-f0fe-11ea-8c50-a2f99eb4c899.png)

It looks great, however, I'd like to add time region, current time,  a bonus feature, anything outside of the region changes red... 

Thanks!

**Comment by marcusolsson** [comment]
That would be a cool feature! Thanks for the detailed feature request! I don't see it being too much work to implement either. I imagine most of the work involves building a custom editor for time regions. 

I've mostly been working on the [Static](https://github.com/marcusolsson/grafana-static-datasource) data source lately, but I will switch back to work on the heatmap next.

**Comment by securenotebook** [comment]
Awesome! 

The Graph visualization contains a time Zone Region - you may be able to reuse that:
![Annotation 2020-09-08 162624](https://user-images.githubusercontent.com/734683/92452251-63617d80-f1f0-11ea-883a-ea259e5c8daa.png)

Let me know if you require a beta-tester,  i will also check out Static

**Comment by marcusolsson** [comment]
Unfortunately, the Graph panel hasn't been migrated to React yet so it's not using the new plugin APIs. On the plus side, we might be able to contribute the Time Region editor back to Grafana 👍 

I might be able to look at this by the end of this week. I'll let you know when I have something testable!

**Comment by securenotebook** [comment]
Ok, understood, thanks I will check back later in the week
