### ISSUE TITLE
u is not a function

### ISSUE THREAD

**Issue by gsouf** [marcusolsson/grafana-hourly-heatmap-panel#13]
Using the hourly timemap I'm getting this error during the configuration of the heatmap

![image](https://user-images.githubusercontent.com/3215399/94841096-d047ec00-0419-11eb-9cc4-86c4b6b9c16e.png)

**Comment by marcusolsson** [comment]
Thank you for reporting this! Can you consistently reproduce this? If so, could you give me the instructions?

**Comment by gsouf** [comment]
@marcusolsson I think this occurs when we select "table" as datatype instead of time series
