### ISSUE TITLE
Frame for each time group

### ISSUE THREAD

**Issue by ChrizZz90** [marcusolsson/grafana-hourly-heatmap-panel#17]
Hey guys, is it possible to add a frame for each time group to have each time slot visually separated? After that I think it is easier to identify each time group, especially if the colors are similar.

**Comment by marcusolsson** [comment]
Either we can add a border to each bucket, or alternatively we could add some padding between each bucket. Either way shouldn't be too much work.

**Comment by marcusolsson** [comment]
Added an option for toggling a cell border

<img width="1236" alt="Screen Shot 2020-12-07 at 10 42 21" src="https://user-images.githubusercontent.com/8396880/101335003-e5f1eb80-3878-11eb-81e7-96040ada06f1.png">

**Comment by ChrizZz90** [comment]
Thanks Marcus! Brilliant and extremely fast update

**Comment by marcusolsson** [comment]
Thanks! The next release will be a bigger one, but I'm aiming for a 0.9.0 release this week.

**Comment by marcusolsson** [comment]
Available in [v0.9.0](https://grafana.com/grafana/plugins/marcusolsson-hourly-heatmap-panel?version=0.9.0) 🎉
