### ISSUE TITLE
Color option for null values

### ISSUE THREAD

**Issue by MaheshKhanal** [marcusolsson/grafana-hourly-heatmap-panel#23]
If there is a null value in the data, the heatmap prints black color. It would be nice to have a color palette to select a color for null values.

**Comment by marcusolsson** [comment]
Sounds like a good feature 👍 Could you share some details on your use case?

I'm not sure when I'll be able to implement this, but the more votes this issue gets the higher it'll get prioritized.

**Comment by KatrinaTurner** [comment]
I just submitted a pull request that implements this. #24 :)
