### ISSUE TITLE
Grafana v7.5.3/7.5.4 - Color scheme doesn't work

### ISSUE THREAD

**Issue by ChrizZz90** [marcusolsson/grafana-hourly-heatmap-panel#25]
I use the heatmap panel in 1 dashboard 3 times. 1 of 3 is displayed without issues, but the other 2 are just without a color. Adding new heatmaps or changing the data doesn't help. It looks like the issue is to have multiple heatmaps in 1 dashboard.

Also I tried to use another color scheme but this doesn't solve it too.

![image](https://user-images.githubusercontent.com/53112257/115032840-0f2b2400-9eca-11eb-8d1f-a621e411c649.png)

**Comment by marcusolsson** [comment]
Thanks for taking the time to report this. I've tried to reproduce this by creating three heatmaps using the Grafana data source in one dashboard. It looks ok to me.

Is there any way you can provide a configuration that reproduces the issue?

**Comment by ChrizZz90** [comment]
I don't know where I should search? What kind of configuration do you need?

The heatmap which works requests data from Postgres and gets: datetime, capacity, utilization.

`2021-04-22 11:00:00 | 31 | 22
2021-04-21 12:00:00 | 31 | 17
...`

The other 2 heatmaps which are dark use the data again. One shows the capacity and the other one the utilization.

The field configuration options are:
- Grouped by 60 min
- Calculation: Sum
- Color palette: RdYlGn
- Invert color palette: True

The panel configuration is:
- Show cell border: True
- Show Tooltip: True
- From: 9:00
- To: 22:00

**Comment by ChrizZz90** [comment]
I got the source of this issue. The working heatmap shows the data in percent (utilization/capacity). The other 2 heatmaps show the absolute figures (31 or 22/17). If I change the unit of these 2 heatmaps to percent I get the colors back. But this can't solve the issue. Any ideas?

**Comment by ChrizZz90** [comment]
I could solve that issue based on Field -> Color Palette -> Field options and choosing Field -> Color Scheme -> Green to Red

**Comment by marcusolsson** [comment]
I'm glad it worked out for you! Thank you for updating the issue 🙏
