### ISSUE TITLE
Doesn't seem to work with 3rd party mongodb datasource

### ISSUE THREAD

**Issue by ycsin** [marcusolsson/grafana-hourly-heatmap-panel#34]
Hi, is there a way for this to work with 3rd party mongodb datasource like [mongodb-grafana-backend](https://github.com/PhracturedBlue/mongodb-grafana-backend)?

**Comment by marcusolsson** [comment]
I'm not familiar with the MongoDB data source, but I'm pretty certain it's possible. What errors are you getting?
