### ISSUE TITLE
Display broken when time range is more than 17 days

### ISSUE THREAD

**Issue by zoechi** [marcusolsson/grafana-hourly-heatmap-panel#5]
![image](https://user-images.githubusercontent.com/405837/87038815-91294680-c1ee-11ea-90cf-f6b4ceeb277a.png)

The black spaces become higher and higher the longer the selected time span is

![image](https://user-images.githubusercontent.com/405837/87038929-b74ee680-c1ee-11ea-9cfa-2c27add532de.png)

It doesn't change for longer than a year time spans anymore

**Comment by marcusolsson** [comment]
Thanks for reporting this! I'm currently on vacation so I probably won't be able to look at this until after next week.

**Comment by marcusolsson** [comment]
Had a chance to look into this finally. The reason the data disappears seems to be that the query returns more than the max number of data points allowed. 

<img width="950" alt="Screen Shot 2020-09-11 at 18 56 08" src="https://user-images.githubusercontent.com/8396880/92952565-7a0e0b80-f460-11ea-852a-243cf62ea281.png">

Could you try and see whether it works if you click Query options, and increase it to the number of rows returned by your query. I'm not sure if this is something panel plugins can control tbh.

**Comment by marcusolsson** [comment]
I've added a Troubleshooting section to the README. Hopefully, that will help anyone experiencing this for now. Closing for now, but feel free to reopen 👍

**Comment by zoechi** [comment]
Sorry for the late response. Increasing Max data points allows to display dates for larger time ranges.
Thanks a lot for looking into the issue and providing this nice plugin 👍
