### ISSUE TITLE
Add option to reverse the color scheme?

### ISSUE THREAD

**Issue by cbwest3** [marcusolsson/grafana-hourly-heatmap-panel#7]
First of all, great tool. I never used carpet-plot, but this panel is a great addition to my dashboard.

I'm trying to display event occurrences and highlight clusters of events. A high count of event occurrences is currently shown with the white end of the color scale while a low count is shown with a deep color (red/green/etc). Is it possible to reverse (or have an option to reverse) the color scheme so that a the high number of occurrences are shaded deeply with the chosen color scheme? Thanks again!

**Comment by glynternet** [comment]
@cbwest3, this is possible by creating a custom colour scheme.

The following is how I have set one of mine up. If you choose your thresholds to be done by percentage, then 0% will be whatever your lowest value is and 100% will be your highest value. Choose your desired colours and you should be ready to go :+1: 

![image](https://user-images.githubusercontent.com/1295698/89120248-ba1abf80-d4ac-11ea-8ffe-8a0d5383bfb7.png)

There may also be other ways of doing this, too.

**Comment by marcusolsson** [comment]
@glynternet is right, you can do this with custom colors. Though I agree it would be handy, and easy, to add a Reverse option to reverse the predefined palettes. I try looking into this during the week!

**Comment by cbwest3** [comment]
Wonderful, thanks for the information @glynternet and @marcusolsson!

**Comment by MaheshKhanal** [comment]
@marcusolsson  I recently made a pull request to you that does the exact same thing. Please take a look at it.

**Comment by marcusolsson** [comment]
This is now available in v0.5.0.

**Comment by cbwest3** [comment]
The changes look great, thanks @MaheshKhanal & @marcusolsson!
